// Hand-pixelled front sprites for Marle, Lucca and Robo.
(function () {
  const CAST = (window.CAST = window.CAST || {});
  CAST.marle = { name: 'Marle', group: 'npcs', w: 24, h: 44,
    pal: {"H": "#5a2804", "d": "#b0640e", "r": "#e0a02a", "R": "#f6cc50", "o": "#fde88c", "y": "#fffbe0", "F": "#ffd4a4", "S": "#f49a70", "s": "#b85c48", "j": "#401408", "P": "#ff7878", "W": "#ffffff", "e": "#d8d0b0", "k": "#10306c", "g": "#3c7ce8", "I": "#ffffff", "i": "#dcdcf4", "c": "#9c9cc4", "p": "#281a3a", "Y": "#f8c040", "n": "#b87818", "A": "#ffc860", "B": "#f48c28", "C": "#b8541a", "q": "#3c1406", "Z": "#1e0e06", "M": "#6a3414", "N": "#a8622a", "w": "#b87c40", "x": "#6a3c1c", "X": "#d0d4e8", "v": "#6c7090"},
    rows: [
      '................HH..HH..',
      '...........HHH.HIiHHIiH.',
      '.........HHoRRHHIicciIcH',
      '........HoRRRRRdHHccHHH.',
      '.......HoRRoRRRRdHHRdH..',
      '......HoRRdoRRRRRdHoRdH.',
      '.....HoRdoRRRdoRRdHoRrdH',
      '....HoRRdoRRdoRRRdHRoRdH',
      '...HoRdoRRdoRRdoRdHRRrdH',
      '...HRoRdHoRRdHoRdHHoRrdH',
      '...HRRdHRRdHRRdHRdHRRrdH',
      '...HRdHSSHdHSSsHdHHoRrdH',
      '...HRHsSSsSSSsSSHdHRRrdH',
      '...HRHSjeksskejSHdHRrRdH',
      '...HRHSjWgSSgWjSHdHoRrdH',
      '...HrHsPFFsSFFPsHdHRRrdH',
      '....HHHjSSSjjSSSjHHRrRdH',
      '.......jSSSSSSSj.HRRrdH.',
      '......pIIjsSsjIIp.HoRdH.',
      '.....pIIiFFYFFiIcp.HRrdH',
      '....pIIIiIFnFIiIicp.HrdH',
      '...pIiIIiIIFIIiIiicpHRdH',
      '...pIipIIiIIIIiIcpcpHrdH',
      '...pFFppIIiIIIicppFSpHdH',
      '..pFFp.pIIiIIIicp.pFSpHH',
      '..pFSp.pIIIiIIicp.pSSp.H',
      '..pIIp.pBBBYBBBCp.pIcp..',
      '..piip.pAABnBBCCp.picp..',
      '..pFFpqAABBBBBBCqpFSp...',
      '..pSSpqAABBqBBBCCqpSsp..',
      '..xwwxqAABBqBBBCCq.pp...',
      'XXxwxXXqABBqqBBCCq......',
      'vXvwxXvXqABq.qBCCq......',
      '...xwx..qAAq.qBBCq......',
      '...xwx..qABq.qBBCq......',
      '...xxx..qABq.qBCCq......',
      '........qABBq.qBCCq.....',
      '........qAABq.qBBCq.....',
      '........qABBq.qBBCCq....',
      '.......ZNMMMZ.ZMMNMZ....',
      '.......ZNMMMZ.ZMMMMZ....',
      '......ZNMMMMZ.ZMMNMMZ...',
      '......ZNNMMMZ.ZMNNMMZ...',
      '......ZZZZZZZ.ZZZZZZZ...',
    ] };
  CAST.lucca = { name: 'Lucca', group: 'npcs', w: 24, h: 40,
    pal: {"G": "#0e2a16", "v": "#2a6634", "V": "#3f9a4c", "L": "#8ad87a", "l": "#d4f4c0", "b": "#6a3a18", "K": "#221410", "c": "#5a4868", "u": "#ffd070", "U": "#d08020", "H": "#28104a", "h": "#56308e", "R": "#8a5ac8", "o": "#bc98f0", "F": "#ffd4a4", "S": "#f49a70", "s": "#b85c48", "j": "#401408", "P": "#ff8080", "W": "#ffffff", "X": "#d8ecff", "g": "#6a4020", "A": "#ffb458", "B": "#ee8430", "C": "#b0521a", "p": "#2a1208", "T": "#62c062", "t": "#3a8a44", "Q": "#1c4a26", "n": "#7a4a2a", "y": "#f0c850", "x": "#a8b0c8", "Z": "#1e0e06", "M": "#6a3414", "N": "#a8622a"},
    rows: [
      '........................',
      '.........GGGGGG.........',
      '.......GGVVLLVVGG.......',
      '......GVVLllLVVVvG......',
      '.....GVVLLLVVVVVvvG.....',
      '.....GVVVVVVVVVvvvG.....',
      '....GbKKKKbbbbKKKKbG....',
      '....GKuuUKbbbbKuuUKG....',
      '....GKuUUKGGGGKuUUKG....',
      '...HGGKKKKhRRhKKKKGGH...',
      '..HRoRhRRhRRRhRRhRRohH..',
      '..HRoRHshhSSSShhsHRRhH..',
      '..HRRHSSccSSSSccSSHRhH..',
      '..HoRHScWgccccgWcSHRhH..',
      '..HRRhSSccSFSSccSShRRH..',
      '..HoRhHsSSFsSFSSsHhRoH..',
      '...HRhHHSSSjjSSSHHhRH...',
      '..HoRhH.jSSSSSSj.HhRoH..',
      '...HHH.pTjsssjTp..HHH...',
      '......pTTtTTTTtTQp......',
      '....ppAATtTTTtTQCpp.....',
      '...pAAABpAABBBpBCCCp....',
      '...pAABpAABBBBCpCCCp....',
      '...pAABpAABBBBCpBCCp....',
      '...pFFSpAABBBBCpSFFp....',
      '...pSSppAABBBBCppSSp....',
      '...pFFpnnnnynnnnpFFp....',
      '...pSSpnxnnnnnnnpSSp....',
      '....pp.pAABBBBCCp.pp....',
      '.......pTTtTTtQQp.......',
      '.......pTttpTtQQp.......',
      '.......pTtp.ptQQp.......',
      '.......pSFp.pFSSp.......',
      '.......pSFp.pFSsp.......',
      '.......pSSp.pSSsp.......',
      '......ZNMMZ.ZMMNZ.......',
      '......ZNMMZ.ZMMMZ.......',
      '.....ZNMMMZ.ZMMNMZ......',
      '.....ZNNMMZ.ZMNNMZ......',
      '.....ZZZZZZ.ZZZZZZ......',
    ] };
  CAST.robo = { name: 'Robo', group: 'npcs', w: 30, h: 42,
    pal: {"O": "#3a1c06", "C": "#9a561a", "c": "#d88a2c", "h": "#f2b648", "y": "#fff0a8", "n": "#56606e", "m": "#8c96a6", "u": "#cad2de", "v": "#1a1c2c", "V": "#34384e", "e": "#ff3c28", "E": "#ffd0b0", "a": "#48c4f0", "A": "#e0fbff", "b": "#1c5a8a"},
    rows: [
      '..............OO..............',
      '.............OaAO.............',
      '.............ObaO.............',
      '..............Om..............',
      '...........OOOmnOOO...........',
      '.........OOhhyyhhccOO.........',
      '........OhhyyhhhhhccCO........',
      '.......OhhyhhhhhhhhhcCO.......',
      '.......OhhhhhhhhhhhhcCO.......',
      '.....OOOVvvvvvvvvvvvvvOOO.....',
      '....OuuOVvEeVvvvvEeVvvOmnO....',
      '....OumOVveeVvvvveeVvvOmnO....',
      '.....OOOVvvvvvvvvvvvvvOOO.....',
      '.......OhccnmnmnmnmccCO.......',
      '........OhccccccccccCO........',
      '.........OOCCCCCCCCOO.........',
      '...........OnmmmmnO...........',
      '..OOOO...OOOOOOOOOOOO...OOOO..',
      '.OuumnO.OhhyyhhhhhccCO.OmmnnO.',
      'OuumnnnOhhyhhhhhhhhhcCOmmnnnnO',
      'OummnnnOhhhOOOOOOOOhcCOmnnnnnO',
      'OmmnnnnOhhhOaAAaabOhcCOnnnnnnO',
      '.OnnnnOhhhhOaabbabOhccCOnnnnO.',
      '..OOOOOhhhhOOOOOOOOhccCOOOOO..',
      '...OmOOhhhhhhhhhhhhhccCOOmO...',
      '...OnO.OhhhhhhhhhhhhccCO.OnO..',
      '...OmO.OhhhhhhhhhhhccCCO.OmO..',
      '..OhcCOOhhhhhhhhhhhccCCOOhcCO.',
      '.OhhccCOOhhhhhhhhhccCCOOhhccCO',
      '.OhyhcCO.OhhhhhhhcccCO.OhyhcCO',
      '.OhhhcCO.OOhhhhhccCCOO.OhhhcCO',
      '.OhhccCO..OOCCCCCCCOO..OhhccCO',
      '..OCCCO...OnmmmmmmnO....OCCCO.',
      '...OOO....OmmmmmmmmO.....OOO..',
      '..........OnmO..OmnO..........',
      '..........OmnO..OmnO..........',
      '..........OnmO..OmnO..........',
      '........OOhhcCO.OhhcCOO.......',
      '.......OhhyhccCOOhhhccCO......',
      '.......OhhhhccCOOhhhccCCO.....',
      '.......OCCCCCCOOOCCCCCCO......',
      '........OOOOOOO.OOOOOOO.......',
    ] };
})();
