// Hand-pixelled cast sprites (bosses). See CAST_SPEC.md.
(function () {
  const CAST = (window.CAST = window.CAST || {});

  // TYRANO: rust tyrannosaur, 3/4 front, jaws open to the left, tail sweeping right
  CAST.tyrano = {
    name: 'Tyrano', group: 'bosses', w: 64, h: 56,
    pal: { K: '#2a0806', s: '#561608', d: '#8a2e12', m: '#bc4e1c', l: '#e07a30', h: '#f8b456', u: '#f4d8a0', U: '#cc9c5c', v: '#8e5a32', w: '#fffaf0', W: '#c8b49a', M: '#3a0610', r: '#b82838', R: '#e8645a', E: '#fce068', e: '#140808', c: '#ece2c8', C: '#9c8a6c' },
    rows: [
    '',
    '................KKKKKKKK',
    '............KKKKhhhllllmmKKK',
    '.........KKKhhllllllllllmmmKK',
    '.......KKhhlllllllllllsssmmmdK',
    '.....KKhlllllllllllllsKKKKsmmddK',
    '...KKhlllllllllllllmsKwEEeKsmmddK',
    '..KhlllKKlllllllmmmmsKEEeeKsmmdddK',
    '.KhllllllllllllmmmmmmsKKKKsmmmdddK',
    '.KllmmmmmmmmmmmmmmmmmmssssmmmmddddK',
    '.KmmmdddddmmmmmmmmmmmmmmmmmmmmdddddK',
    '..Ksddddddddddmmmmmmmmmmmmmmmdddddds',
    '..KwKwwKwwKwwKwKsdddddmmmmmdddddddsdK',
    '...KwKWKWwKWKwKwKKsddddmmmmmmddddsddK',
    '....KMKMKMKMKMMMMMKsdddddmmmmmdddddddK',
    '...KMMMMrrrrrrrRRMMMKsdddddmmmdddddddds',
    '...KMMrrRRRRRRrrrrrMMKsddddmmmmmdsdddsdK',
    '...KwMMrrrrrrrrrMMMMwKKsdddmmmmmmdddsdddK',
    '...KwKwMMMMMMMMMMMwKwKKsddmmddllmddsddddKKK',
    '....KwWKwKwKwKwKwKWKsKsddmmmllllmmdddddddsKK',
    '.....KKmmmmmmmmmmmmmsKKsdmmlllllddmdddddsddsK',
    '......KKsdddddddddddsKuUsdmmlllhlmmmdddsddddsK',
    '........KKKKKKKKKKKKKuuUvsdmllllllmmmdsmdddddssK',
    '...................KuuuUUvsdmmmlllllmmmmddddsdddsK',
    '..................KUUUUUvvsdmmlllllmdmmmmddsdddddsK',
    '.................KuuuuuUUvsdmmmlllllmmmmmdsmddddsdsK',
    '..............KKKKuuuuUUvvsddmmmllllmmmmmmdddddsddmsK',
    '.............KhlmdKuuuUUvsddmmmmmddmmmmmmmddddsddddmmK',
    '............KhllmdsKUUUUvvsdmmmmmmmdmmmmmmdddsddddddmmK',
    '...........KhlmmdsKKuuuUvsdssssssssmmmmmdddKKKKdddsdmllK',
    '...........KlmmdsK.KuuUUvsslllllllssmmmmKKKmmmmKKsdsdmllK',
    '...........KmddsK..KUUUvvslllhhlllllsmmmKmmllmmmdKsddsmllK',
    '...........KcKcK...KuuUUvsllhhhllllllsmmKmllmmmdddsKsdmllK',
    '...........KCKCK...KuuUvvsllhhllllllllsmKmlmmmdddddsKsddmlK',
    '............K.K....KUUUvvslllllllllllllsKmmmmddddddsKdsdmlK',
    '...................KuuUvvslmmllllllllllsKmmmdddddddsKddsdmlK',
    '....................KvvvsdlllllllllllllmKmmdddddddssKsddsmlK',
    '.....................KsdmlllllllllmmlmmsKmdddddddssKssdddsmlK',
    '......................KsdmllllllllllmmmsKsddddddssKdsssddsmlK',
    '......................KsdmmllmmllllmmmmsKsdddddssKddddsssdmmlK',
    '.......................KsdmmmllllmmmmmsKKsddddssKKKssddssdmmlK',
    '.......................KKsdmmmmmmmmmmsKKKsddddsKK.KKKKssddsdmlK',
    '........................KKsddmmmmmddssK.KsdmdsK.......KKKsddmlK',
    '..........................KKsddddddsKK..KsdmdsK..........KKKdmK',
    '............................KsdlmmdsK...KsdmdsK.............KKK',
    '............................KsdlmmdsK...KsdmdsK',
    '...........................KsdlmmmdsK...KsddmsK',
    '...........................KsdlmmmdsK...KsddmsK',
    '..........................KsdlmmmmdsK..KsdddmsK',
    '.........................KsddmmmmmdsK..KsddddsK',
    '.......................KKsdmmlllmmddK.KKsddddsK',
    '......................KKKKsdmllllllmmdK.KsdmmmddsK',
    '....................KKcKcKcdmlllhhllmdKKcKcddmmmdsK',
    '...................KcCKcCKcCmmmmmmmmdKKcCKcCKdddddsK',
    '...................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    ],
  };

  // LAVOS SPROUT: a miniature Lavos. Plated, spiked shell; a beaked head glowers out from under the rim
  CAST.lavos_sprout = {
    name: 'Lavos Sprout', group: 'bosses', w: 34, h: 31,
    pal: { K: '#1c0c14', a: '#3e2630', b: '#64404a', c: '#8e6462', C: '#bc9080', x: '#fff4dc', X: '#dcc8a4', Y: '#a88c6c', y: '#6c5444', q: '#6e0e1e', r: '#c42a34', R: '#f26a4a', e: '#fce068', E: '#ffffff', M: '#1a060c', h: '#5a1c26', H: '#8c3834' },
    rows: [
    '................KK',
    '................KxK',
    '...K...........KxXK...........K',
    '...KK..........KxXYK.........KK',
    '...KxK........KxXXYK........KyK',
    '...KXxK.......KxXYYK.......KYyK',
    '....KXxK......KxXYYyK.....KYyK',
    '.....KXxK.....KxXXYyK....KYyK',
    '......KYXxK...KxXYYyK...KYyK',
    '.......KCYXKKKKKKYyKKKKKYyK',
    '........KCYKccbbbKKbbaaKyK',
    'KK.....KCcccKabbbbbbbKaaaaK.....KK',
    'KxKK..KCcccKabbbbbbbbbKaaaaK..KKyK',
    '.KXxKKKKcccccbbbbbbbbbbaaaKKK.KYyK',
    '..KKKCCCKKKcbbbbbbbbbbbKKKbbaK.KK',
    '...KCcccCCCKKKKKKKKKKKKbbbaaaaK',
    'KK.KCcccKacCccccccccccbaaKaaaaK.KK',
    'KxKKCccKacccbbbbKabbbbbaaaKaaaKKyK',
    '.KXxKcccccccbbbbKabbbbbaaaaaaaKYyK',
    '..KKKCCCCCCccccccccccbbbbbbbbbKK',
    '...KKaaaaaaaaaaaaaaaaaaaaaaaaKK',
    '....KKMMMMMhhhKKKKKKhhhhhhhMMMMKK',
    '.....KMMMhhHHKRRRrrrKhhhhHHhhMMMK',
    '.....KMMhHKKKKRxRrrqKhhhKKKhHMMMK',
    '.....KMhKeEeKKRRRrrqKhKKeEeKhMMMK',
    '.....KMhKKeeeKKRRrqKKhhKeeeKKhMMK',
    '.....KMMhhKKKKMKRrqKMhhhKKKhhMMMK',
    '......KKMMMhhhKKRrqKhhhhhhhMMMKK',
    '..KKxXKKKKKKKKKMKrqKhhhMMKKKYyKK',
    '..KxXcXK........KKK.......KYyYyK',
    '..KKKKKK..................KKKKKK',
    ],
  };

  // LAVOS SPROUT (LARGE): grown in the crater. a miniature Lavos. Plated, spiked shell; a beaked head glowers out from under the rim
  CAST.lavos_sprout_large = {
    name: 'Lavos Sprout (large)', group: 'bosses', w: 48, h: 40,
    pal: { K: '#1c0c14', a: '#3e2630', b: '#64404a', c: '#8e6462', C: '#bc9080', x: '#fff4dc', X: '#dcc8a4', Y: '#a88c6c', y: '#6c5444', q: '#6e0e1e', r: '#c42a34', R: '#f26a4a', e: '#fce068', E: '#ffffff', M: '#1a060c', h: '#5a1c26', H: '#8c3834' },
    rows: [
    '.......................KK',
    '.......................KxK',
    '......................KxXK',
    '....K.................KxXYK...............K',
    '....KK................KxXYK..............KK',
    '....KxK..............KxXXYK.............KyK',
    '....KXxK.............KxXYYyK...........KYyK',
    '.....KXxK............KxXYYyK..........KYyK',
    '......KXxK.....K....KxXXYYyK....K....KYyK',
    '.......KYXxK..KxK...KxXYYYyK...KyK..KYyK',
    '........KYXxK.KxK...KxXYYYyyK..KYK.KYyK',
    '.........KYXxKKXxK..KxXXYYYyK..KYyKYyK',
    '..........KYXxKXYKKKKxXYYYyyKKKKYyKyK',
    '...........KYXKXYKaCCKKYYyyKbaKKYyKK',
    'KK.........KKCYKKacbbbbKKKbbbbaKKKKKK.........KK',
    'KxKK......KCCKCYKccbbbbbbbbbbbaKKKbbaK......KKyK',
    '.KXxKK..KCCcKaCCCKKKKKKKKKKKKKKbbbaKaaKK..KKYyK',
    '..KKXxKKCccKaccccccKacccccccKabbaaaaKaaaK.KYyKK',
    '....KKKKKcccccccccKabbbbbbbbbKabaaaaaaaKKK.KK',
    '.....KCCCKKKcccccbKabbbbbbbbbKabbaaaKKKbbaK',
    'KK...CCccCCCKKcccKabbbbbbbbbbbKabaKKbbbaaaK...KK',
    'KxKKKCccccKaCCKKKKKKKKKKKKKKKKKKKKbbaKaaaaaKKKyK',
    '.KXxKCcccKacccCCCccccccKacccccbbbbaaaaKaaaaKYyK',
    '..KKKCcccccccccccbbbbbbKabbbbbbbbaaaaaaaaaaKKK',
    '....CCcccccccccccbbbbbKabbbbbbbbbaaaaaaaaaaK',
    '...KCCCCCCCCCCccccccccccccccccbbbbbbbbbbbbbbK',
    '...KKaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaKK',
    '.....KKMMMMMMMhhhhhhhhhhhhhhhhhhhhhhhhMMMMMMKK',
    '......KMMMMMhhHHHHhhhhhhhhhhhhhhhhHHHHhhMMMMK',
    '......KMMMMhHHKKKhhhKKKKKKKKKhhhhhhhKKKhHMMMK',
    '......KMMMhHhhhKKKhKRRRRRRrrrKhhhKKKhhhhhMMMK',
    '......KMMMhhhKeeEeKKRxRRRRrrqKhKKeEeeKhhhMMMK',
    '......KMMMhhhKKeeeeKRxRRRrrrqKhKeeeeKKhhhMMMK',
    '......KMMMMhhhhKKKKKKRRRRrrrqKKhKKKKhhhhMMMMK',
    '......KMMMMMhhhhhhhKMKRRRrrqKMKhhhhhhhhMMMMMK',
    '......KKMMMMMMhhhhhKqKKRRrrqKKqKhhhhMMMMMMKKK',
    '.......KKKKKMMMMMMhhKqKKRrqKKqKhMMMMMMKKKKK',
    '...KKxXKK............KK.KRqK.KK........KKYyKK',
    '...KxXcXK...............KrqK...........KYyYyK',
    '...KKKKKK................KK............KKKKKK',
    ],
  };

  // VITRINE SENTINEL: a walking museum display case. Brass cornice and plinth, glass with glints, a porcelain skull on a velvet cushion, stubby porcelain legs
  CAST.vitrine = {
    name: 'Vitrine Sentinel', group: 'bosses', w: 32, h: 44,
    pal: { K: '#1a1420', n: '#fff0a0', N: '#f0c048', o: '#b87c2c', O: '#6e4218', i: '#2c4260', j: '#44648a', J: '#6c90b4', G: '#b4dcf4', W: '#ffffff', P: '#f6f6fa', p: '#d2d6e4', q: '#9ca2bc', Q: '#5c6282', B: '#c4f0ff', b: '#4ca8e8', V: '#e05060', v: '#a82838', u: '#5c1020' },
    rows: [
    '...............KK',
    '..............KnNK',
    '.............KnNoOK',
    '..KKKKKKKKKKKKNNooKKKKKKKKKKKKK',
    '.KNNNNNNNNNNNoooooooooooooooOOOK',
    '.KnnnnnnnNNNNNNNNNNNNNNNNNNoooK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KnNNoNNoNNoNNoNNoNNoNNoNNoNNoOOK',
    'KoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOK',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    '.KnNKiiiiiiiiiiiiiiiiiiiiiiKoOK',
    '.KnNKNoGJGjjjjjjjjjjjjjjjOoKoOK',
    '.KnNKoGWGJGjjjjjjjjjjjjjGjOKoOK',
    '.KNoKjJGWGJjKKKKKKKKjjjjGjiKoOK',
    '.KNoKjjJGWGKPPPqPPPpKjjjGiiKoOK',
    '.KNoKjjjJGKPPPPPqPpppKjjGiiKoOK',
    '.KNoKjjjjJKPKKKqpqKKKKjiGiiKoOK',
    '.KNoKjjjjjKKBbBKpKBbBKjiGiiKoOK',
    '.KNoKijjjjKPKbKPpqKbKKiiGiiKoOK',
    '.KNoKiijjjjKPPPKKpqqKjiiiiiKoOK',
    '.KNoKiiijjjKPKPKpKqKKiiiiiiKOOK',
    '.KNoKiiiijjjKKKKKKKKiiiiiiiKOOK',
    '.KNoKiiiiKnVVVVVVvvvvvnKiiiKOOK',
    '.KNoKiiiKVVVVVVVVvvvvvvuKiiKOOK',
    '.KoOKiiiKvVVVVvvvvvvvvuuKiiKOOK',
    '.KoOKOJJJKnuuuuuuuuuuunKJJOKOOK',
    '.KoOKoJJJJKKKKKKKKKKKKKJJJOKOOK',
    '.KoOKoOJJJJJJJJJJJJJJJJJJOOKOOK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KnNNNNNNNNNNNNNNNNNNNNNNNNNNNooK',
    'KPPPPPPPPPPPPPPPPPPPPPPPPPPPppqK',
    'KPPppppppppKKKKKKKKKKpppppppppqK',
    'KPpppppppppKnNNNNNNoKpppppppppqK',
    'KPpqqqqqqqqKKKKKKKKKKqqqqqqqqqQK',
    'KoooooooooooooooooooooooooooOOOK',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    '..KPPppK..KqQK....KQQK.KPppqK',
    '..KPPPpqK.KqQK....KQQK.KPPpqqK',
    '..KPPPpqK.KqQK....KQQK.KPPpqqK',
    '...KPpqK..KoOK....KoOK..KPqqK',
    '...KPpqK..KKKK....KKKK..KPqQK',
    '...KPpqK................KPqQK',
    '..KNnooOK..............KNooOOK',
    '..KKKKKKK..............KKKKKKK',
    ],
  };

  // THE CURATOR (phase 1): porcelain egg head with a slit eye, dead-grey docent's coat hanging open on a lattice of blue light, long porcelain fingers
  CAST.curator_p1 = {
    name: 'The Curator', group: 'bosses', w: 40, h: 64,
    pal: { K: '#16141f', W: '#ffffff', P: '#eceef6', p: '#c4c8da', q: '#8e92ac', Q: '#5a5e7a', C: '#9a9cab', c: '#72748a', d: '#50526a', D: '#2e2f40', B: '#e6f8ff', b: '#7cc8ff', L: '#3a7ad8', l: '#243e78', n: '#f0c048', o: '#a8702a' },
    rows: [
    '.................KKKKKK',
    '...............KKWPpPPpKK',
    '..............KWPPPqPPppqK',
    '.............KWPPPPqPPPppqK',
    '.............KWPPPPKKPPppqK',
    '.............KPPPPKbBKPpQqK',
    '.............KPPPPKLBKPQqqK',
    '.............KPPPPKbBKPqqqK',
    '.............KPPPPKLBKPpQqK',
    '.............KPPPPKbBKppqqK',
    '.............KpPPPKLbKppqqK',
    '............K.KpPPPKKPppqK.K',
    '...........KCKKppPPPPPpqqKKdK',
    '...........KCcKKppPPPppqKKcdK',
    '...........KCcKDKqpppqqKDKcdK',
    '...........KCcKDDKqqqqKDDKcdK',
    '...........KCcKDDDKKKKDDDKcdK',
    '.........KKKCcCKDDKpqKDDKcddKKK',
    '........KCCKCccCKDKpqKDKcdddKcdK',
    '.......KCCCKCcCKBbKPpKbLKcddKcddK',
    '.......KCCCKCCKPPPPPppppqKcdKcddK',
    '.......KCCCKCCKBbbKPpKbbLKcdKcddK',
    '.......KCCCKCCKPPPPPppppqKcdKcddK',
    '.......KCCCKCCKBbbKPpKbbLKcdKcddK',
    '.......KCCCKCCKPPPPPppppqKcdKcddK',
    '.......KCCCKCCKBbbKPpKbbLKcdKcddK',
    '.......KCCCKCCKPPPPPppppqKcdKcddK',
    '.......KCCCKCcCKBbKPpKbLKcddKcddK',
    '.......KCCCKCcCKPPPPpppqKcddKcddK',
    '.......KCccKCccCKbKPpKLKcdddKcDDK',
    '.......KcCCKCcccCKPPpqKcddddKDddK',
    '.......KCCCKCccccCKPpKcdddddKcddK',
    '.......KCCCKCccccCKnoKcdddddKcddK',
    '.......KCCCKCccccCKooKcdddddKcddK',
    '.......KCccKCccccccKcnddddddKcddK',
    '.......KCccKCcdccccKcdndDdddKcddK',
    '.......KCccKCcdccccKcnKoDdddKcddK',
    '......KCCccKCcdccccKcdodDdddKcdddK',
    '......KCCccKCcdccccKcdndDdddKcdddK',
    '......KCCCCKCcdccccKcdodDdddKccddK',
    '......KKKKKKCcdccccKcdooDdddKKKKKK',
    '.......KPPpKCcdccccKcdddDdddKpqqK',
    '......KWPPpqKcdccccKcdddDdKPppqQK',
    '......KPPPpqKcdccccKcdddDdKppqqQK',
    '......KPKPKqKcdccccKcdddDdKpKqKQK',
    '......KPKPKqKcdccccKcdddDdKpKqKQK',
    '......KPKPKqKcdcccKDKdddDdKpKqKQK',
    '......KPKPKqKcdcccKDKdddDdKpKqKQK',
    '......KPKPKqKcdccKDDDKddDdKpKqKQK',
    '......KPKPKKKcdccKDDDKddDdKKKqKQK',
    '......KPKPKCcdccKDDDDDKdDdddKqKQK',
    '......KKKPKCcdccKDDDDDKdDdddKqKKK',
    '.........KCcdccKPpKDKpqKdDdddK',
    '.........KCcdcDKPpKDKpqKDdDddK',
    '........KCcdcDDKPpKDKpqKDDdDddK',
    '........KCcdDDDKPpKDKpqKDDDdDdK',
    '.......KCCcDDDDKPpKDKpqKDDDDcddK',
    '.......KKKKKKKKKPpK.KpqKKKKKKKKK',
    '...............KPpK.KpqK',
    '...............KQQK.KQQK',
    '...............KPpK.KpqK',
    '..............KPPpK.KppqK',
    '.............KWPPpK.KppqQK',
    '.............KKKKKK.KKKKKK',
    ],
  };

  // THE CURATOR (phase 2): porcelain plates opened like a flower around a knot of Lavos-red energy; split head, flung arms, tattered coat
  CAST.curator_p2 = {
    name: 'The Curator (Core Exhibit)', group: 'bosses', w: 56, h: 64,
    pal: { K: '#16141f', W: '#ffffff', P: '#eceef6', p: '#c4c8da', q: '#8e92ac', Q: '#5a5e7a', C: '#9a9cab', c: '#72748a', d: '#50526a', D: '#2e2f40', B: '#e6f8ff', b: '#7cc8ff', L: '#3a7ad8', Y: '#fff6c8', o: '#ffb040', R: '#f04030', r: '#b01828', m: '#5c0818', M: '#2a0410' },
    rows: [
    '',
    '',
    '',
    '.....................KKKK.rRRr.KKKK',
    '...................KKWPPPrRoRrmpppqKK',
    '..................KWPPPPPrRoRrmpppqqqK',
    '..................KWPPPPKrooormKppqqqq',
    '..................KPPPPKmroYormmKpqqqK',
    '.....KK...........KPPPPKrroYormrKpqqQK...........KK',
    '.....KWKK.........KPPPPKRroYormRKpqqQK.........KKPK',
    '.....KWPPKK.......KPPPPKrroYormrKpqqQK.......KKppPK',
    '......KWPPPKK.....KpPPPKmrooormmKpqqQK.....KKpppPK',
    '......KWPPPPPKK....KpPPPKrRoRrmKpqqq.K...KKpppppPK',
    '.......KWPPPPPPKK..KppPPPrRoRrmppqqQK..KKppppppPK',
    '.......KWPPPPPPPpKK.KppPKrRoRrmKpqQK.KKqpppppppPK',
    '.K......KWPPPbPPPpqK.KKK...RR...KKK.KQqpppLpppPK......K',
    'KPK..K..KPPPPPbPPpqqK.....KpqK.....KQQqppLpppppK..K..KpK',
    '.KPK.KPK.KPPPPPbPppqK.....KQQK.....KQqqpLpppppK.KpK.KpK',
    '..KPKKPK.KpPPPPPbppqQK....KpqK....KQQqqLpppppqK.KpKKpK',
    'KK.KPPPK..KpPPPPPbpqQK...KKQQKK...KQQqLpppppqK..KpppK.KK',
    'KPKKPPWPKKKqpPPPPPbqQK.KKmKpqKmKK.KQQLpppppqQKKKpPppKKpK',
    '.KPPPPPpqqKKqpPPPPpbrKKmrRmmmRRrmKKrLqppppqQKKQQqpppppK',
    'KKKPPPppqqqqKqppPPpqbrmRRoooorrRRmrLQqppqqQKQQQQqqpppKKK',
    'KPPPKKpqqqqqqKqqppqqKmRorooYRRoroRmKQQqqQQKQQQQQQqKKpppK',
    '.KKK..KKqqqqqqKKqqqKmRororYYYYRorRrmKQQQKKQQQQQQKK..KKK',
    '........KKqQQQQQKKKKmRroRrRYYYYRrRrmKKKKQQQQQQKK',
    '........KKKKKKKKK.KmRorRYYrYYYYRroRrmK..KKKKKKKK',
    '.....KKKWWPPPPKKRoKmRroRYYYRYYYrooRrmK.KKKppppPPKKK',
    '...KKWWPPPPPPPPPKKKmRmRYYYYYYRrYooRrmKKqpppppppppPPKK',
    '.KKWPPPPPbbbbPPPppKmRmooYYYYYYYooRRrmKqqpppLLLLpppppPKK',
    '.KWPPPbbbPPPPbbbrrRmrmooYYYRYYYooRmrmRrrLLLppppLLLpppPK',
    '..KKpPPPPPPPPPPppqKmrRRooYrRYYooRRmmmKrRKppppppppppqKK',
    '....KKqpppPPPpppqQKKmrRooorRYooRRmrmKKQKqqqpppqqqQKK',
    '......KKKqqqqqqQKK.KmrRRooorRRRRrrmmK.KKQQQQQQQKKK',
    '.........KKKKKKK....KmrRRRoorrrrrrmK....KKKKKKK',
    '.................KKKKKmrrRRRRRRrrmKKKKK',
    '...............KKqqqQKKmmrrrrrrmmKKQQQQKK',
    '..............KqqppqqRKKKmmmmmmKKKRQQqqQQK',
    '.............KqppPPprbK..KKKKKK..KLrqppqqQK',
    '............KqpPPPPrbKrK.........KQLrppppqQK',
    '...........KqpPPPPPbqQK..........KQQLpppppqQK',
    '...........KpPPPPPbpqQK..........KQQqLpppppqK',
    '..........KpPPPPPbppqQKKKKKKKKKKKKQQqqLpppppqK',
    '..........KPPPPPbPppqKccKDDDDDDDDKKQqqpLpppppK',
    '.........KPPPPPbPPpqqKccKDDDDDDDDKKQQqppLpppppK',
    '.........KPPPPbPPPpqKcccKDDDDDDDDKdKQqpppLpppPK',
    '........KPPPPPPPPpKKdccccKDDDDDDKdddKKqpppppppPK',
    '........KPPPPPPPKKcdcccccKDDDDDDKddddDKKppppppPK',
    '.......KPPPPPPKKcccdccccccKDDDDKdddddDddKKpppppPK',
    '.......KPPPPKKKCccdcccccccKDDDDKddddddDddKKKpppPK',
    '......KPPPKK..KCccdccccccccKDDKdddddddDdddK.KKppPK',
    '......KPKK...KCcccdcccccccccKKddddddddDdddK...KKPK',
    '......KK.....KCccdccccccccccKdddddddddDddddK....KK',
    '.............KCccdcccccKcccccKdddddKddDddddK',
    '............KCcccdccccKKccccKddddddKKdDdddK',
    '............KCccdcccccK.KccccKdddddK.KdDddK',
    '............KCccdccccK..KcccKdddddK...KdddK',
    '............KCcdccccK....KccKddddK....KddK',
    '.............KcdcccK.....KcKKdddK......KdK',
    '.............KcdccK.......K..KddK.......K',
    '..............KcdK...........KdK',
    '..............KcK.............K',
    '...............K',
    ],
  };
})();
