// Hand-pixelled cast sprites (villagers). See CAST_SPEC.md.
(function () {
  const CAST = (window.CAST = window.CAST || {});
  // Shared skin / eye ramps (Crono's).
  const SKIN = { F: '#ffcc9c', S: '#ff8468', s: '#af584a', j: '#230c08', W: '#ffffff', e: '#c7c7a3' };

  // ---- 600 A.D. farmer: green cap with a drooping tip, brown vest over linen, belt.
  CAST.villager_600 = {
    name: 'Farmer (600)', group: 'villagers', w: 22, h: 40,
    pal: Object.assign({}, SKIN, {
      C: '#12301a', c: '#2c6430', v: '#488c34', V: '#78b848', w: '#b0e070',
      H: '#2a140a', h: '#4a2a16', r: '#6e4222', R: '#9c6434',
      k: '#2a1a10', g: '#7a4a24',
      p: '#281820', L: '#f0e4c8', l: '#c8b494', D: '#8c7460',
      T: '#b07a40', U: '#80502a', Q: '#4a2a16',
      b: '#1e120a', B: '#3a2414', G: '#e0b050',
      K: '#140c0c', n: '#b4a684', m: '#8c7c62', M: '#6a5a48', d: '#443a30',
      Z: '#1b0f07', o: '#4d2c17', I: '#8c5634', J: '#c08a5c',
    }),
    rows: [
      '........CCCC',
      '......CCwVVvCC',
      '.....CwVVVvvvvC',
      '....CVwVVvvvvvcC',
      '....CVVvvvvvvvccCC',
      '...CVVvvvvcvvcccvcC',
      '...CVvvvvvcvvccCCvcC',
      '..CVvvvcvvvvccCC.CvcC',
      '..CVVVVVVVVVvvvvC.CcC',
      '..CcccccccccccccC..CC',
      '...HRhHrRhHRrhHrRH',
      '...HrRHsSSsSSsSHRrH',
      '...HRhHjeksskejHhRH',
      '....HRSjWgSSgWjShH',
      '.....HsSFFsFFSsH',
      '......jSSSjjSSj',
      '......pDjsssjDp',
      '.....pUTlLLLlUQp',
      '....pUTTUlLDlUUQp',
      '...pTUTTUQlLlQUUQUp',
      '...plTpTUQlLlQUQpDlp',
      '...pLlpTUQlLlQUQplDp',
      '..pLlDpTUQlLDQUQpDlDp',
      '..pLlppTUQlLlQUQppDlp',
      '..pLlp.pBBBGBBBp.pDlp',
      '..pSFp.pbbbGbbbp.pSSp',
      '..pFSppTUQlLlQUQppSsp',
      '...pp.pTUQlDlQUUQp.pp',
      '......ppppKmKpppp',
      '......KmmMdK.KmMMdK',
      '......KmmMdK.KmMMdK',
      '......KmnMdK.KmnMdK',
      '.....KmnmMdK.KmMMddK',
      '......KmMMdK.KMMMdK',
      '......KmMddK.KMMddK',
      '.....ZoIoZ...ZoIoZ',
      '.....ZIJooZ.ZoIooZ',
      '....ZoIJoooZ.ZoIooZ',
      '....ZIJIoooZ.ZoIIooZ',
      '....ZZZZZZZ.ZZZZZZZ',
    ],
  };

  // ---- 600 A.D. market wife: cream kerchief, red dress, white apron, basket on her arm.
  CAST.villager_600_b = {
    name: 'Market wife (600)', group: 'villagers', w: 24, h: 39,
    pal: Object.assign({}, SKIN, {
      X: '#5a3416', A: '#fff4c0', a: '#e8c878', n: '#b88c48',
      H: '#2a140a', h: '#4a2a16', r: '#6e4222', R: '#9c6434',
      k: '#2a1a10', g: '#7a4a24',
      p: '#3a0c14', c: '#e04848', t: '#a82434', T: '#6c1422',
      L: '#ffffff', l: '#dcdcec', D: '#a4a4c0',
      b: '#6c1422',
      Y: '#4a2a10', x: '#e0a850', y: '#a8702c', O: '#e03a2a', o: '#ffd060', G: '#58a038',
      Z: '#1b0f07', M: '#4d2c17', I: '#8c5634',
    }),
    rows: [
      '.......XXXXXX',
      '.....XXAAAAAaXX',
      '....XAAAAnaaaaaX',
      '...XAAAaaanaaaanX',
      '...XAAaaaaannaanX',
      '..XAAaaaaaaaannnnX',
      '..XAanaaaaaaaanannX',
      '..XaanXXXXXXXXXnnX',
      '..XaXHrRhHhRrhHXnX',
      '..XaHrHsSSsSSsSHXnX',
      '..XaXHHjjksskjjHXnX.X',
      '..XnX.HjWgSSgWjSXnXXaX',
      '...XnXHsSFFsFFSsXnXanX',
      '...XXX.jSSSjjSSjXXXnX',
      '.......pcjsssjtp..XX',
      '......pcttLLLlttp',
      '.....pcttpLLLlpttp',
      '....pcctTpLLLlptTtp',
      '...pcctpTpLLLlpTtptp',
      '...pctppTpLLllpTtpptp',
      '...pctp.pLLLlDp.pttp',
      '..pcttp.pLLllDp.pttTp',
      '..pSFFp.pbbbbbp.YpFSpY',
      '..pFFSp.pLLllDpY.pSp.Y',
      '...ppp.pcLLllDpYYYYYYYY',
      '......pcLLLllDYxxxxxxyY',
      '......pctLLllDYxOoGOxyY',
      '.....pcttLLllDYOOGOOyyY',
      '.....pcttLLlllYxxxxxyyY',
      '.....pcttLLllDYyxyxyyY',
      '....pctcTLLLllDpYYYYYp',
      '....pcttTLLlllDDpTttTp',
      '....pcttcTLlllDDpTttTp',
      '...pcttctTpppppptTttTtp',
      '...pcttcttTttcttTttTttp',
      '...pppppppppppppppppppp',
      '......ZMIMZ...ZMMIZ',
      '.....ZMIMMZ...ZMMIMZ',
      '.....ZZZZZZ...ZZZZZZ',
    ],
  };

  // ---- 600 A.D. old man: bald dome, grey fringe, bushy brows and moustache, blue tunic,
  // brown vest, stooped over a walking stick.
  CAST.villager_600_c = {
    name: 'Old man (600)', group: 'villagers', w: 22, h: 37,
    pal: Object.assign({}, SKIN, {
      E: '#fff0dc',
      H: '#34344c', h: '#6e7090', r: '#a4a8c4', R: '#e8ecf4',
      p: '#1c1830', c: '#8cb8f0', t: '#5c90dc', T: '#3c64b4', Q: '#243c7c',
      U: '#9c6434', u: '#6e4222', V: '#40220e',
      b: '#2a160e', G: '#dcb468',
      y: '#c08a4c', Y: '#6a3c18', q: '#2e1a0c',
      K: '#140c0c', m: '#7a665a', M: '#5a4a44', d: '#3e3230',
      Z: '#1b0f07', o: '#4d2c17', I: '#8c5634',
    }),
    rows: [
      '',
      '',
      '........jjjjj',
      '......jjEEFFSjj',
      '.....jEEFFFFSSsj',
      '....jFEFFFFFSSSsj',
      '....jFFFFFFSSSSsj',
      '...HjSFFFFSSSSSssjH',
      '..HRrjSSSSSSSSSsjrhH',
      '..HRrhRRRrSSrRRRHrhH',
      '..HrRhjjjSSSSjjjHhhH',
      '..HhrjsSsSSSSsSsjrhH',
      '...HhjSFFSssFFSsjhH',
      '....HjRRRRrrRRRRjH',
      '....jRRrrjSSjrrRRj',
      '.....jRjSSjjSSjRj',
      '.....pUjjsssjjuVp',
      '....pUUtjjjjjtuuVp',
      '...pUUtctttttTTuuVp',
      '..pcUUpctttttTpuVpTp',
      '..pctUpctttttTpuVpTp',
      '..pctUpctttttTpuVptTp',
      '..pctppctttttTppVptTp',
      '..pctp.pbbbGbbbp.ptTp',
      '..pSFp.pctttttTp.pSSp',
      '..pFFppctttttTTpppSsp',
      '...pp.pcttTtttTTp.pp',
      '...yY.pctTpTttTTp',
      '..yY..pppppKpppppp',
      '..yY..KmmMdKmMMdK',
      '..yY..KmmMdKmMMdK',
      '..yY..KmmMdKmMMdK',
      '.yY...KmMMdKMMddK',
      '.yY...KmMddKMMddK',
      '.yY..ZoIoZ..ZoIoZ',
      'yY..ZoIIooZ.ZoIooZ',
      'qq..ZZZZZZZ.ZZZZZZZ',
    ],
  };

  // ---- 65,000,000 B.C. Ioka hunter: wild black mane, bare chest, hide strap, fur shorts.
  CAST.villager_ioka = {
    name: 'Ioka hunter', group: 'villagers', w: 24, h: 43,
    pal: {
      H: '#0c0a1a', q: '#1e1c36', h: '#34325e', r: '#6064a4', R: '#b4bcf0',
      F: '#f0b07c', S: '#cc7c4c', s: '#8c4a2c', j: '#2a0e06', W: '#ffffff', e: '#d8c8a8',
      k: '#2a1a10', g: '#6a3a1c',
      x: '#3a1e0c', C: '#e8c47c', c: '#a8703a',
      p: '#2a160c', U: '#b07a44', u: '#7a4c26', n: '#4a2a14', A: '#f0dcb0',
      E: '#f4ecd8', D: '#b8a88c',
    },
    rows: [
      '.....H......H......H',
      '....HrH....HrH....HhH',
      '...HrRH...HrRhH..HrhH',
      'H..HrRhH..HrRhH.HrhhH..H',
      'HH.HrRrhH.HrRRhHHrhhH.HH',
      'HrHHrRhhHHrRrhhHrrhhHHhH',
      '.HrRHrRhhHrRrhhHrRhhHhqH',
      'HrRrhHRrhhHrRhhHrhhqHhqH',
      '.HrRhHrRhhHrrhhHrhhHhqH',
      'HrRhHRrhhHrRhhHHrhqHhqqH',
      '.HrhHrrhHrRhhHrHhqHHhqH',
      '.HRhHrhHjHsSSsSSsHhjHhqH',
      'HrhHHrhHSjjjSSSSjjjHhHqH',
      '.HrhHrHHjeksskejHHqHhqH',
      '.HrhHrHSjWgSSgWjSjHqhqH',
      'HrhHHrhHsSFFsFFSsHHqhqH',
      '.HrhHrhHjSSSjjSSjHhHqhH',
      '..HrHHrhpSjsssjSphHqHhH',
      '..HrhH.jsSSjjjSSsj.HqH',
      '...jjjjSFFSSSSSxCxjjjj',
      '..jFFSjSFFSSSSxCcxSjSSj',
      '.jFFFSjsFFSSSxCcxSSjSSsj',
      '.jFFSSjSsssSxCcxsssjSSsj',
      '.jFSSjjSSSSxCcxSSSjjSsj',
      '..jFSj.jSSxCcxSSsj.jSsj',
      '..jSFj.jSxCcxsSsj..jSsj',
      '..jFSj.jxCcxjjjj...jSsj',
      '..jcCj.xUcUxxUUux.jcCj',
      '..jFSsj.xUUAUUUuxjSSsj',
      '..jFSj.xAUUuUUAUux.jSsj',
      '...jj..xUUUUxUuUux..jj',
      '.......xUAUux.xUuux',
      '.......xxxxx..xxxxx',
      '........jSFj..jSsj',
      '........jFSj..jSsj',
      '.......jSFSj..jSSsj',
      '........jSsj..jSsj',
      '.......nEEDn..nEDDn',
      '.......nDnDn..nDnDn',
      '......nEEDDn..nEEDn',
      '......nEDnDDn.nEDnDn',
      '.....nEEEDDDn.nEDDDDn',
      '.....nnnnnnnn.nnnnnnn',
    ],
  };

  // ---- 65,000,000 B.C. Ioka woman: long auburn hair parted in the middle, fur top and
  // skirt, bone-bead necklace.
  CAST.villager_ioka_b = {
    name: 'Ioka woman', group: 'villagers', w: 26, h: 41,
    pal: Object.assign({}, SKIN, {
      H: '#2c0808', h: '#6c1a14', r: '#a03020', R: '#d86038', Y: '#f8a060',
      F: '#f4bc8c', S: '#d88c5c', s: '#9c5434', j: '#2a0e06',
      k: '#3a1a10', g: '#8c4a24',
      x: '#3e200e', A: '#f4e0b4', U: '#d0a060', u: '#9c6834', n: '#6a3a18',
      E: '#fff4e0', D: '#c8b89c',
    }),
    rows: [
      '..........HHHH',
      '........HHRYrrHH',
      '.......HRRYrrhhHH',
      '......HRRYrrhhhHhH',
      '.....HRYrrhhhhHhrhH',
      '....HRRrrhhhHHhhrrhH',
      '....HRrrhhhHSHhhhrrhH',
      '...HRYrhhhHSSSHhhrrhhH',
      '...HRrhhhHFSSSHhhhrhhH',
      '..HRrhhHHFFSSSsHHhhrhhH',
      '..HRrhhHsFFFSSSSsHhrhhH',
      '..HRrhHjjjksskjjjHhrhhH',
      '..HRrhHSjWgSSgWjSHhrhhH',
      '..HRrhHsSFFsFFSsHhhrhhH',
      '..HRrhHsSSSsjSSsHhhrhH',
      '..HRrhHHSssSssSHHhrhhH',
      '..HRrhHjsSSjjjSSsjHhrhH',
      '.HRrhhjSFFSSEsEsSSsjhrhH',
      '.HRrhjSFFSSSsEsSSSSsjhrhH',
      '.HRrjSFFjxAAAUUUUuxjSsjhH',
      '.HRrjSFFjxAUAUUuUuxjSsjhH',
      '.HRrjSFSjjxAUUUuuxjjSSjhH',
      '..HRjFSSj.jSFFSSSsj.jSsjH',
      '..HRjFSj..jSFSSSssj..jSsjH',
      '...HjFSj..jSSsSSsj...jSsH',
      '...HjSSj.xAAUUUUuux..jSSj',
      '....jFSjxAUnUUnUuuux.jSsj',
      '....jFFSxUUUUnUUuuux.jSSsj',
      '.....jjxAUnUUUUnuuuux.jjj',
      '......xAUUUUuUUUuunux',
      '......xUxUUxUUxuuxuux',
      '.......x.xx.xxx.xx.x',
      '........jSFj..jSsj',
      '........jFSj..jSsj',
      '........jSFj..jSsj',
      '........jSsj..jSsj',
      '.......nAADn..nADDn',
      '.......nDnDn..nDnDn',
      '......nAADDn..nAADn',
      '......nADnDDn.nADnDn',
      '......nnnnnnn.nnnnnn',
    ],
  };

  // ---- 65,000,000 B.C. Ioka elder: grey mane, long beard, dark pelt, bone-topped staff.
  CAST.villager_ioka_c = {
    name: 'Ioka elder', group: 'villagers', w: 25, h: 40,
    pal: Object.assign({}, SKIN, {
      F: '#f4bc8c', S: '#d08458', s: '#94502e', j: '#2a0e06',
      H: '#262438', h: '#62647e', r: '#9c9eb8', R: '#e4e6f2',
      x: '#140e0c', C: '#8c7666', c: '#62524a', q: '#3c302c',
      b: '#a8703a', B: '#5a3416',
      y: '#b07c40', Y: '#5a3416', o: '#3c2a1a', E: '#fff4e0', D: '#c8b490',
      n: '#3c2414', A: '#e0cca8', U: '#a08c70',
    }),
    rows: [
      '...................oo.oo',
      '...................oEoEEo',
      '....................oEDDo',
      '.....................oEo',
      '.....................oEo',
      '........H..H........oEoEo',
      '......HHrHHrHH.H....oEDDo',
      '....HHrRhHrRhHrHHH...oo',
      '...HrRrhHrRrhHrRhhH..yY',
      '..HrRhhHrRhhHHrhhHhH.yY',
      '..HRhhHrhhHHsSSHHrhhHyY',
      '..HrhHHsSSsSSsSSHHrhHyY',
      '..HRhHRRRrSSrRRRHhrhHyY',
      '..HrhHsjjjSSjjjsHhhH.yY',
      '...HhHSsSSSsSSsSHhhH.yY',
      '...HhRsSFFsFFSsRhhH..yY',
      '....HRRrRRRrRRrRRhH..yY',
      '....HRrRRrrrRrrRrhH..yY',
      '...xxHRrRRrRrrRhhHxxxyY',
      '..xCcxHRrRrRrrhhHxcqxyY',
      '.xCCccxHRrRRrhhHxccqxoo',
      '.xCcccxHrRrRrhHxcccxoSSo',
      '.xCcxqcxHrRrhhHxccxqoFSo',
      '.xCcxjSxcHRrhHxcqxjoSsSo',
      '..xxjSFjxcHrhHxcqxj.oyYo',
      '...jSFSjxCcHhHcccqx.xyY',
      '...jFSj.xbbbbBbBBx...yY',
      '...jSSj.xCcccccqqx...yY',
      '...jFSsjxCcxccxcqx...yY',
      '....jjjxCcxcccxcqqx..yY',
      '.......xCxcxcqxcqx...yY',
      '.......xx.xxxx.xx....yY',
      '........jSFj.jSsj....yY',
      '........jFSj.jSsj....yY',
      '........jSFj.jSsj....yY',
      '.......nAAUn.nAUUn...yY',
      '.......nUnUn.nUnUn...yY',
      '......nAAUUn.nAAUn...yY',
      '......nAUnUUnnAUnUn..yY',
      '......nnnnnnnnnnnnn..oo',
    ],
  };

  // ---- 12,000 B.C. Last Village elder-ish robed man: slate hood and mantle with white fur
  // trim, hands tucked into his sleeves, long brown wool robe.
  CAST.villager_last = {
    name: 'Robed man (12000 BC)', group: 'villagers', w: 22, h: 40,
    pal: Object.assign({}, SKIN, {
      X: '#16142a', u: '#6a5a8c', U: '#4a3c68', V: '#30264a',
      I: '#f6f8ff', i: '#c8cce4', J: '#8488a8',
      H: '#2a140a', h: '#5a3418',
      k: '#1a2a3a', g: '#4a7aa0',
      p: '#1a1830', c: '#9496bc', t: '#6e7098', T: '#4c4e74',
      b: '#2a160e', G: '#dcb468',
      Z: '#1b0f07', o: '#4d2c17', y: '#8c5634',
    }),
    rows: [
      '.........XXXX',
      '.......XXuuUUXX',
      '......XuuuUUUUVX',
      '.....XuuUUUUUUVVX',
      '....XuuUUUUUUUUVVX',
      '...XuuUIIIIIiiiUVVX',
      '..XuUIIIIiIiiiiiJVVX',
      '..XuIiJhhhhhhhhJiJVX',
      '.XuIIiHhsSSsSShHiJVVX',
      '.XuUIiHjeksskejHiJVVX',
      '.XuUIiSjWgSSgWjSiJVVX',
      '.XuIIisSFFsFFSsHiJVVX',
      '.XuUIijSSSjjSSjiJVVX',
      '.XuUIIIijsssjiiiJVVX',
      '.XuuUUIIIiiiiiJUUVVVX',
      'XuuUUUUUIIiIIUUUUVVVX',
      'XuUUUUUUUUUUUUUUUVVVVX',
      'XuUUUUUUUUUUUUUUUVVVVX',
      'XIIiIIiIIiIiiIiiiJiJJX',
      '.XIiiIIiiIiiiIiiJJJX',
      '.pccttpttTtTTTpTTTtTp',
      '.pccctttpTtTpTTTTtTTp',
      '.pccccttIIJIiJTTTTtTp',
      '..pcctttIipiiJTTTTtp',
      '..pcctTTttttTTTTTtTp',
      '..pbbbbbbbbGbbbbbbbp',
      '..pcctTcctttTcttTTTp',
      '..pcctTcctttTcttTTTp',
      '..pcctTccttTTcttTTTp',
      '.pccctTccttTTcttTTTTp',
      '.pcctTTccttTcctTTTTTp',
      '.pcctTcccttTcctTTTTTp',
      '.pcctTcccttTcctTtTTTp',
      'pccctTccttTTccttTTTTTp',
      'pcctTTccttTcccttTTTTTp',
      'pcctTcccttTcccttTTTTTp',
      'pcctTTcctTTcctTTtTTTTp',
      'pppppppppppppppppppppp',
      '....ZoyoZ....ZoyoZ',
      '...ZZZZZZ....ZZZZZZ',
    ],
  };

  // ---- 12,000 B.C. Last Village woman: rounded white wool hood with tan fur, teal shawl
  // pinned by her hands, long brown dress.
  CAST.villager_last_b = {
    name: 'Shawl woman (12000 BC)', group: 'villagers', w: 22, h: 39,
    pal: Object.assign({}, SKIN, {
      X: '#34345a', u: '#f8faff', U: '#cfd4ea', V: '#9498ba',
      I: '#ecd4aa', i: '#c4a27a', J: '#8a6848',
      H: '#2a140a', h: '#5a3418',
      k: '#1a3a3a', g: '#3a8a84',
      m: '#0c2a2e', A: '#6ccab8', a: '#2e948a', M: '#1c5e60',
      p: '#1e120e', c: '#a4806a', t: '#7a5c4c', T: '#543e34',
      Z: '#1b0f07', o: '#4d2c17', y: '#8c5634',
    }),
    rows: [
      '.......XXXXXX',
      '.....XXuuuuUUXX',
      '....XuuuuuUUUUVX',
      '...XuuuUUUUUUUVVX',
      '...XuuUUIIIIIiUVVX',
      '..XuuUIIIIiIiiiJVVX',
      '..XuUIiJhhhhhhJiJVVX',
      '.XuIIiHhhSSsShhHiJVVX',
      '.XuUIiHjjksskjjHiJVVX',
      '.XuUIiSjWgSSgWjSiJVVX',
      '.XuIIisSFFsFFSsHiJVVX',
      '.XuUIisSSSsjSSsiJVVX',
      '.XuUIIIisSSSsiiiJVVX',
      '.XuuUUIIIiiiiiJUUVVVX',
      '..XuUUUUUUUUUUUVVVX',
      '.mAAXXUUUUUUUUXXaMm',
      'mAAaaAXXXXXXXXaaaaMm',
      'mAaaAaaaaaaaaaaaaaMMm',
      'mAaaaAaaaaaaaaaaaMMMm',
      'mAaamAaaaaaaaaaaMmMMm',
      '.mAamAaaaaaaaaaaMmaMm',
      '.mAamSFSmaaaamSSsmaMm',
      '.mmm.pmFSAaaaSsmp.mmm',
      '.....pcmAaaaaMMp',
      '.....pctmAaaMmTp',
      '.....pcttmAMmtTTp',
      '....pcctt.m.ttTTp',
      '....pcctTcttTttTTp',
      '....pcctTcttTttTTp',
      '...pccctTcttTtttTTp',
      '...pcctTccttTtttTTp',
      '...pcctTccttTttTTTTp',
      '..pccctTccttTttTTTTp',
      '..pcctTcccttTtttTTTTp',
      '..pcctTcccttTtttTTTTp',
      '..pcctTTcctTTttTTTTTp',
      '..ppppppppppppppppppp',
      '.....ZoyoZ...ZoyoZ',
      '....ZZZZZZ...ZZZZZZ',
    ],
  };

  // ---- 12,000 B.C. Last Village spear hunter: teal parka hood with white fur, belted parka,
  // slate trousers, fur boots, a stone-tipped spear.
  CAST.villager_last_c = {
    name: 'Spear hunter (12000 BC)', group: 'villagers', w: 23, h: 39,
    pal: Object.assign({}, SKIN, {
      F: '#f4bc8c', S: '#d08458', s: '#94502e', j: '#2a0e06',
      X: '#0a2226', u: '#58b8a0', U: '#2e7c74', V: '#1c4c50',
      I: '#f6f8ff', i: '#c8cce4', J: '#8488a8',
      H: '#1a0c06', h: '#3a2010',
      k: '#1a2a3a', g: '#3a6a90',
      b: '#3a2010', G: '#c8ccd8',
      K: '#141428', m: '#7a7ca0', M: '#585a80', d: '#3a3c5a',
      n: '#3c2414', A: '#f0e4cc', D: '#b8a88c',
      y: '#b07c40', Y: '#5a3416', o: '#2a1a0c',
      q: '#2a3a5a', W: '#ffffff', w: '#b8dcf8',
    }),
    rows: [
      '....................qq',
      '...................qWwq',
      '...................qWwq',
      '...................qwwq',
      '.........XXXX.......qq',
      '.......XXuuUUXX....oYYo',
      '......XuuUUUUUVX....yY',
      '.....XuuIIIIiiVVX...yY',
      '....XuIIIiiiiiiJVX..yY',
      '...XuIiJhhhhhhJiJVX.yY',
      '..XuIiHhsSSsSShHiJVXyY',
      '..XuIiHjeksskejHiJVXyY',
      '..XuIiSjWgSSgWjSiJVXyY',
      '..XuIisSFFsFFSsHiJVXyY',
      '..XuIijSSSjjSSjiJVX.yY',
      '..XuIIIijsssjiiiJVX.yY',
      '..XuUIIIiiiiiiJUVX..yY',
      '..XXuUIIiiiiJUUXX...yY',
      '.XuuXuUUIiiJUUVXVVX.yY',
      'XuuUXuUUUIiUUUVVXuVVXY',
      'XuUUXuUUUIiUUUVVXuUVXY',
      'XuUX.XuUUIiUUUVX.XuVXY',
      'XuUX.XuUUIiUUVVX.XuVVX',
      'XIiX.XbbbbGbbbbX.XIiJX',
      'XSFX.XuUUIiUUUVX..XSFSX',
      'XFSXXuuUUIiUUUVVX.XFSSX',
      '.XX.XuuUUUIiUUUUVX..XX',
      '...XuuUUUUIiUUUUVVX.yY',
      '...XIIiIIiIIiiIiiJX.yY',
      '....XXXXXXXXXXXXXX..yY',
      '.....KmmMdK.KmMMdK..yY',
      '.....KmmMdK.KmMMdK..yY',
      '.....KmmMdK.KMMMdK..yY',
      '.....KmMMdK.KMMddK..yY',
      '....nAAADn..nAADn...yY',
      '....nAnDDn..nADnDn..yY',
      '...nAAADDn..nAADDn..yY',
      '...nADnDDDn.nADnDDn.yY',
      '...nnnnnnnn.nnnnnnn.yY',
    ],
  };

  // ================================ props ================================
  // ---- The Epoch: winged time machine, nose to the left, seen a little from the front.
  CAST.epoch = {
    name: 'Epoch', group: 'props', w: 58, h: 37,
    pal: {
      K: '#161a30', W: '#ffffff', a: '#dde2f0', b: '#aab0cc', c: '#7c82a6', C: '#50567a',
      r: '#e0443c', R: '#8c1c2c', y: '#f8cc40', Y: '#b87818',
      N: '#d8f0ff', G: '#5c90dc', g: '#2c4c9c',
      M: '#3a3a52', e: '#8cc0f0', E: '#ffffff',
    },
    rows: [
      '...............................................KKKKKKK',
      '..............................................KyyyYYK',
      '............................................KKrrrRRK',
      '..........................................KKbrKKKKK',
      '.........................................KbccKaabK',
      '.........................KKKKK.........KKbccCKabK',
      '......................KKKNNNGGKKK....KKbcccCKrrRK',
      '.....................KNNGGGGKGGggK..KbccccCCKrRRK',
      '....................KNGGGGGGKGggggKKbccccCCKabbK',
      '...................KNGGGGGGGKGggggKbcccccCCKabbK',
      '...................KNGGGGgggKggggggKbcccCCKabbCK',
      '..................KKKKKKKKKKKKKKKKKKKKbcCCKabCK',
      '..............KKKKWyyyyyyyyyyyyyyyyyYWKKKKKKKKK',
      '...........KKKWWWWWWWWWWWWaaaaaaaaaaaaaaaaaabbcKK',
      '.........KKWWWWWWWaaaaaabaaaaaaaaaaaaaaaabaaabccbK',
      '.......KKWWWWaaaaaaaaaaabaaaaaaaaaaaaaaaabaabbccbKKK',
      '.....KKWWWaaaaaaaaaaaaaabaaaaabbaaaaaaaaababbbccbKKMCM',
      '....KaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbccbKKMCC',
      '...KyyrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRRRCCRKKMCeeEe',
      '..KyyRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRCCRKKMeEEEEE',
      '..KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccKKMeEEee',
      '...KbbbbbbbbccbbbbbbcbbbbbbbbbbbbbbbbbbbcccccccccKKMCee',
      '....KKbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccKcKCCKKMCC',
      '......KKcccccccccccccccccccccccccccccccccccccCCCCKKM',
      '........KKKCCCCCKKKKKKKKKKKKKKKKKKKKKCCCCCCCCCCKK',
      '...........KKKCCCCyyyyyyyyyyyyyyyyyyYKCCCCCCCCK',
      '..............KKKKKKKWWaaaaaaaaaaaabbbKKKKKKKK',
      '.....................KKWWaaaaaaaaaaabbbK',
      '.......................KKWWaaaaaaaaaabbbKK',
      '.........................KWWaaaaaaaaaaabbbK',
      '..........................KKrrrrrrrrrrrrrrrK',
      '............................KKRRRRRRRRRRRRRRK',
      '..............................KKWWaaaaaaaabbbK',
      '................................KKWWaaaaaaabbbKK',
      '..................................KyyyyyyyyyyyyyK',
      '...................................KKYYYYYYYYYYYYK',
      '.....................................KKKKKKKKKKKKKK',
    ],
  };

  // ---- Lavos seed: a spiked carapace egg, dark red, with glowing yellow veins and core.
  CAST.lavos_seed = {
    name: 'Lavos seed', group: 'props', w: 20, h: 23,
    pal: {
      K: '#2a0610', a: '#5c0e1c', A: '#8c1a28', n: '#c43034', N: '#f06a58',
      s: '#3e0a14', t: '#e8b0a0',
      v: '#f08a2c', V: '#fce068', W: '#fff8d0',
    },
    rows: [
      '.........K',
      '........KtK',
      '.......KKssK',
      '...KK.KnnnaaK..KK',
      '..KtsKnNNAAaaKKstK',
      '...KsnNNAAAAaassK',
      '....KNNAAAAAvaKK',
      '...KnNAvAAAvAaaK',
      '...KnnAAvAAvAaaK',
      '...KnnAAvAvAAaaK',
      '.KKnnAvvvvAAvvaaKK',
      'KtsnnAAvAVAAAAaassK',
      '.KsnnAAAAVVAAAaasstK',
      '..KnnAAAAWWVvAaaKKK',
      '...KnnAvVWWAAvaK',
      '...KnvvAAVVAAavK',
      '...KAAAAAAvAAaaK',
      '....KAAaavaaaaKK',
      '...KsAAaavaaaassK',
      '..KtsKAAaavaaKKstK',
      '...KK.KAAaaaK..KK',
      '.......KKssK',
      '........KttK',
    ],
  };

  // ---- Inert Lavos seed: the same shell gone dull grey, cracked through, a dead ember.
  CAST.lavos_seed_inert = {
    name: 'Lavos seed (inert)', group: 'props', w: 20, h: 23,
    pal: {
      K: '#16161f', a: '#3a3a4a', A: '#565668', n: '#78788c', N: '#a4a4b8', k: '#8e8ea2',
      s: '#2a2a38', t: '#9898aa',
      v: '#2c2632', V: '#4c2c34', W: '#7a343c',
    },
    rows: [
      '.........K',
      '........KtK',
      '.......KKssK',
      '...KK.KnnnaKK',
      '..KtsKnNNAAKkKKK',
      '...KsnNNAAKkaassK',
      '....KNNAAAKkvaKK',
      '...KnNAvAAAKkaaK',
      '...KnnAAvAKkAaaK',
      '...KnnAAvKkAAaaK',
      '.KKnnAvvvKkAvvaaKK',
      'KtsnnAAvKVKkAAaassK',
      '.KsnnAKKAVVKkAaasstK',
      '..KnnAAAAWWVKkaaKKK',
      '...KnnAvVWWAKkaK',
      '...KnvvAAVVAAKaK',
      '...KAAAAAAvAAaKK',
      '....KAAaavaaaaKK',
      '...KsAAaavaaaassK',
      '..KtsKAAaavaaKKstK',
      '...KK.KAAaaaK..KK',
      '.......KKssK',
      '........KttK',
    ],
  };

  // ---- Time gate: a standing oval of swirling blue light with a white-hot eye.
  CAST.time_gate = {
    name: 'Time gate', group: 'props', w: 32, h: 39,
    pal: {
      K: '#101c48', g: '#8cc8f8', G: '#e0f4ff', a: '#1c2c6c', b: '#3462c0', c: '#6aa0ec', d: '#b0dcff', e: '#ffffff',
    },
    rows: [
      '.............KKKKK',
      '..........KKKKKKKKKGK',
      '.........KKGGGGGGGGGKK',
      '.......KKGGgggbbbgggggKK',
      '......KKGggaaaaaabbbgggKK',
      '......KGgaaaaaaaaabbbcggK',
      '.....KGgaabbbbbadaaabbcggK',
      '....KGgabbbbbbbbbaaabbbcggK',
      '....KGgbbcccccccbbbaabbcggK',
      '...KGgbbccbbbbbbccbaaabbcggK',
      '...gGbbcbbbbbbbbbccbaabbcbgK',
      '..gGgbcbbbaaaaaabbcbbaabcbggK',
      '..KgbcbbbcaaaaaaabbcbaabbcbgK',
      '..KGbcbbaaabbbbaaabcbaabbcbgK',
      '.KGgcbbaaabbcdddccbbbbabbcbggK',
      '.KGgcbbaabbcdddddcdbcbabbcbggK',
      '.KGcbbaabbcbdddedcdbcbabbcbagK',
      '.KGcbbaabcbdcceeecddcbabbcbacK',
      '.KGcbaabbcbcceeeeeddbaabbcbacK',
      '.KGcbaabcbbcceeeeeddbaabbcbacK',
      '.KgbbaabcbacdeeeeeddbaabcbbacK',
      '.KgbbaabcbacddeeedddaabbcbaacK',
      '.KgbbaabcbaadddedddaaabbcbaacK',
      '.KggbaabcbaadddccccaabbcbaagcK',
      '.KggbaabcbaabdddccabbbccbaagcK',
      '..KgbaabcbbaabcbbbbbbccbaaacK',
      '..KgbaabcbbaabbccbbcccbbaabcK',
      '..Kggaabbcbaaabbccccbbcaabgcg',
      '...KgbaabcbbaaabbbbbbaaaabcKGg',
      '...KggaabccbcaaaaaaaaaaabgcKg',
      '....KggaabcbbbaaaaaaaabbgcK',
      '....KggaabbcbbbbaaaabbbbgcK',
      '.....KggaabbccbbbbbbbbbgcK',
      '......KggaabbcccbbbbccgcK',
      '......KKgggabbbcccccggcKK',
      '.......KKgcgggbbbgggccKK',
      '.........KKcccccccccKK',
      '..........KKKKKKKKKKK',
      '.............KKKKK',
    ],
  };

  // ---- Hollow gate: the same oval gone grey and dead, torn by red scanlines and rows that
  // slip sideways, with a bleeding red eye.
  CAST.hollow_gate = {
    name: 'Hollow gate', group: 'props', w: 34, h: 39,
    pal: {
      K: '#16141e', g: '#9a98ae', G: '#d4d4e2', a: '#2a2436', b: '#4a4658', c: '#6e6c82', d: '#b4b2c6', e: '#ffe8e0',
      r: '#c02c34', x: '#f06c4c',
    },
    rows: [
      '.............KKKKK',
      '..........KKKKKKKKKGK',
      '.........KKGGGGGGGGGKK',
      '.......KKGGgggbbbgggggKK',
      '......KKGggaaaaaabbbgggKK',
      '......KGgrrrrrrrrrbbbcggK',
      '.....KGgaabbbbbadaaabbcggK',
      '....KGgabbbbbbbbbaaabbbcggK',
      '....KGgbbccccdccbbbaabbcggK',
      '.....KGgrrrrrrrrrrrrrrrrrrrggK',
      '.....gGbbcbbbbbbbbbccbaabbcbgK',
      '..gGgbcbbbaaaaaabbcbbaabcbggK',
      '..KgbcbbbcaaaaaaabbcbaabdcbgK',
      '..KGbcbbrrrrrrrrrrrrrrrrrrrgK',
      '.KGgcbbaaabbcdddccbbbbabbcbggK',
      '.KGgcbbdabbcdddddcdbcbabbcbggK',
      '.KGcbbaabbcbdddxdcdbcbabbcbagK',
      '.KGrrrrrrrrxrrxxxrxxrrabbrrrrK',
      '.KGcbaabbcbccxxxxeddbaabbcbacK',
      '.KGcbaabcbbccxxxexddbaabbcbacK',
      '.KgbbaabcbacdxxexxddbaabcbbacK',
      'grrrrrrrrrxxxxxxxxrrrrrrrrrK',
      '.KgbbaabcbaadddxdddaaabbcbdacK',
      '.KggbaabcbaadddccccaabbcbaagcK',
      '.KggbaabcbaabdddccabbbccbaagcK',
      '..KgrrrrrbbarrrrrrrrrrrrrrrrK',
      '..KgbaabcbbaabbccbbcccbbaabcK',
      '..Kggaabbcbdaabbccccbbcaabgcg',
      '...KgbaabcbbaaabbbbbbaaaabcKGg',
      '....KggrrrrrrrrrrrrrrrrrrrgrKg',
      '.....KggaabcbbbaaaaaaaabbgcK',
      '....KggaabbcbbbbaaaadbbbgcK',
      '.....KggaabbccbbbbbbbbbgcK',
      '......KggrrrrrccbrrrrrgrK',
      '......KKgggabbbcccccggcKK',
      '.......KKgcgggbbbgggccKK',
      '.........KKcccccccccKK',
      '..........KKKKKKKKKKK',
      '.............KKKKK',
    ],
  };
})();
