// Hand-pixelled cast sprites (bosses). See CAST_SPEC.md.
(function () {
  const CAST = (window.CAST = window.CAST || {});

  // TYRANO: rust tyrannosaur, 3/4 front, jaws open to the left, tail sweeping right
  CAST.tyrano = {
    name: 'Tyrano', group: 'bosses', w: 64, h: 56,
    pal: { K: '#2a0806', s: '#561608', d: '#8a2e12', m: '#bc4e1c', l: '#e07a30', h: '#f8b456', u: '#f4d8a0', U: '#cc9c5c', v: '#8e5a32', w: '#fffaf0', W: '#c8b49a', M: '#3a0610', r: '#b82838', R: '#e8645a', E: '#fce068', e: '#140808', c: '#ece2c8', C: '#9c8a6c' },
    rows: [
    '',
    '................KKKKKKKK',
    '............KKKKhhhllllmmKKK',
    '.........KKKhhllllllllllmmmKK',
    '.......KKhhlmlllllllllsssmmmdK',
    '.....KKhlllllllllllllsKKKKsmmddK',
    '...KKhlllmlllllllllmsKEEEeKsmmddK',
    '..KhlllKKlllllllmmmmsKEEeeKsmmdddK',
    '.KhlllmllllllllmmmmmmsKKKKsmmmdddK',
    '.KllmmmmmmmmmmmmmmmmmmssssmmmmddddK',
    '.KmmmdddddmmmmmmmmmmdmmmmmmmmmdddddK',
    '..Ksddddddddddmmmmmmmmmmmdmmmdddddds',
    '..KwKwwKwwKwwKwKsdddddmmmmmmmdddddsdK',
    '...KwKWKWwKWKwKwKKsddddmmmmmmddddsddK',
    '....KMKMKMKMKMMMMMKsdddddmmdmmdddddddK',
    '...KMMMMrrrrrrrRRMMMKsdddddmmmmddddddds',
    '...KMMrrRRRRRRrrrrrMMKsddddmmmmmdsdddsdK',
    '...KwMMrrrrrrrrrMMMMwKKsdddmmdmmmdddsdddK',
    '...KwKwMMMMMMMMMMMwKwKKsddmmmmllmddsddddKKK',
    '....KwWKwKwKwKwKwKWKsKsddmmmllllmmdddddddsKK',
    '.....KKmmmmmmmmmmmmmsKKsdmmlllllmmmdddddsddsK',
    '......KKsdddddddddddsKuUsdmmlllhlmmmdddsddddsK',
    '........KKKKKKKKKKKKKuuUvsdmllldllmmmdsmdddddssK',
    '...................KuuuUUvsdmlllllllmmmmddddsdddsK',
    '..................KUUUUUvvsdmmllllllmmmmmddsdddddsK',
    '.................KuuuuuUUvsdmmmllldlmmmmmdsmddddsdsK',
    '..............KKKKuuuuUUvvsddmmmllllmmmmmmdddddsddmsK',
    '.............KhlmdKuuuUUvsddmmmmmmmmmmdmmmddddsddddmmK',
    '............KhllmdsKUUUUvvsdmmmmmmmdmmmmmmdddsddddddmmK',
    '...........KhlmmdsKKuuuUvsdssssssssmmmmmdddKKKKdddsdmllK',
    '...........KlmmdsK.KuuUUvsslllllllssmmmmKKKmmmmKKsdsdmllK',
    '...........KmddsK..KUUUvvslllhhlllllsmmmKmmllmmmdKsddsmllK',
    '...........KcKcK...KuuUUvsllhhhllllllsmmKmllmmmdddsKsdmllK',
    '...........KCKCK...KuuUvvsllhhlllllmllsmKmlmmmdddddsKsddmlK',
    '............K.K....KUUUvvslllllllllllllsKmmmmddddddsKdsdmlK',
    '...................KuuUvvslllllmlllllllsKmmmdddddddsKddsdmlK',
    '....................KvvvsdlllllllllllllmKmmdddddddssKsddsmlK',
    '.....................KsdmllllllllllllmmsKmdddddddssKssdddsmlK',
    '......................KsdmllmlllllllmmmsKsddddddssKdsssddsmlK',
    '......................KsdmmllllllllmmmmsKsdddddssKddddsssdmmlK',
    '.......................KsdmmmllllmmmmmsKKsddddssKKKssddssdmmlK',
    '.......................KKsdmmmmmmmmmmsKKKsddddsKK.KKKKssddsdmlK',
    '........................KKsddmmmmmddssK.KsdmdsK.......KKKsddmlK',
    '..........................KKsddddddsKK..KsdmdsK..........KKKdmK',
    '............................KsdmmmdsK...KsdmdsK.............KKK',
    '............................KsdmmmdsK...KsdmdsK',
    '...........................KsdmmmmdsK...KsddmsK',
    '...........................KsdmmmmdsK...KsddmsK',
    '..........................KsdmmmmmdsK..KsdddmsK',
    '.........................KsddmmmmmdsK..KsddddsK',
    '.......................KKsdmmlllmmddK.KKsddddsK',
    '......................KKKKsdmllllllmmdK.KsdmmmddsK',
    '....................KKcKcKcdmlllhhllmdKKcKcddmmmdsK',
    '...................KcCKcCKcCmmmmmmmmdKKcCKcCKdddddsK',
    '...................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    ],
  };

  // LAVOS SPROUT: a miniature Lavos. Plated, spiked shell; a beaked head glowers out from under the rim
  CAST.lavos_sprout = {
    name: 'Lavos Sprout', group: 'bosses', w: 34, h: 31,
    pal: { K: '#1c0c14', a: '#3e2630', b: '#64404a', c: '#8e6462', C: '#bc9080', x: '#fff4dc', X: '#dcc8a4', Y: '#a88c6c', y: '#6c5444', q: '#6e0e1e', r: '#c42a34', R: '#f26a4a', e: '#fce068', E: '#ffffff', M: '#1a060c', h: '#5a1c26', H: '#8c3834' },
    rows: [
    '................KK',
    '................KxK',
    '...K...........KxXK..........K',
    '...KK..........KxXYK........KK',
    '....KxK........KxXYK.......KyK',
    '....KXxK......KxXXYyK.....KYyK',
    '.....KXxK.....KxXYYyK....KYyK',
    '......KXxKKKKKxXXYYyKKKKKYyK',
    '.......KYXCCCcxXYYYybbbbYyK',
    '......KCCYXCCccxXYYycbbbYaK',
    '.....KCCCCcKacccKYYKbbKabbaaK',
    '....KCKKccKacccbbKKbbbbKabKKaK',
    'KK..KCCCKKKccbbbbbbbbbbKKKbbaaK.KK',
    'KxKKCCccCCCKKKKKKKKKKKKbbbbaaaKKyK',
    '.KXxCcccKabCCcccccccccbbbKaaaaKyK',
    '..KXKKcKabbbbKabbbbbKabbbbKaKKKK',
    '..KKCCKKKbbbKabbbbbbbKabbKKKbbaK',
    '...KCcCCCKKKKKKKKKKKKKKKKbbbaaaK',
    'KK.KCccbbCCCCcccKaccccbbbbbaaaaK.K',
    'KxKCCCCcccccccccccbbbbbbbbbbaaaaKy',
    '.KXKccccbbbbbbbbbbbbbbbbbbbaaaaKyK',
    '..KKKKaaaaaaaaaaaaaaaaaaaaaaaKKKK',
    '....KKKMMMhhhhhhhhhhhhhhMMMMKKK',
    '.....KMMhHeEKhhRRRrrhhKEehhMMK',
    '.....KMMhHeeeKhRxRrrqhKeeehMMK',
    '.....KMMhHhKKhRRRRrrrqhKKhhMMK',
    '......KMMhHhhKRRrrrrqqKhhhMK',
    '......KMMMhhhhKRrrrqqKhhhMMK',
    '.....KKKKMMhhhKKrrqKhhMMKKKK',
    '....KxXcKKKKKKKKrqKKKKKKYyK',
    '....KKKKK.......KK.....KKKK',
    ],
  };

  // LAVOS SPROUT (LARGE): grown in the crater. a miniature Lavos. Plated, spiked shell; a beaked head glowers out from under the rim
  CAST.lavos_sprout_large = {
    name: 'Lavos Sprout (large)', group: 'bosses', w: 48, h: 40,
    pal: { K: '#1c0c14', a: '#3e2630', b: '#64404a', c: '#8e6462', C: '#bc9080', x: '#fff4dc', X: '#dcc8a4', Y: '#a88c6c', y: '#6c5444', q: '#6e0e1e', r: '#c42a34', R: '#f26a4a', e: '#fce068', E: '#ffffff', M: '#1a060c', h: '#5a1c26', H: '#8c3834' },
    rows: [
    '.......................KK',
    '.......................KxK',
    '......................KxXK',
    '....K.................KxXYK...............K',
    '....KK................KxXYK..............KK',
    '....KxK..............KxXXYK.............KyK',
    '....KXxK.............KxXYYyK...........KYyK',
    '.....KXxK............KxXYYyK..........KYyK',
    '......KXxK.....K....KxXXYYyK....K....KYyK',
    '.......KYXxK..KxK...KxXYYYyK...KyK..KYyK',
    '........KYXxK.KxK...KxXYYYyyK..KYK.KYyK',
    '.........KYXxKKXxK..KxXXYYYyK..KYyKYyK',
    '..........KYXxKXYKKKKxXYYYyyKKKKYyKyK',
    '...........KYXKXYKaCCKKYYyyKbaKKYyKK',
    'KK.........KKCYKKacbbbbKKKbbbbaKKKKKK.........KK',
    'KxKK......KCCKCYKccbbbbbbbbbbbaKKKbbaK......KKyK',
    '.KXxKK..KCCcKaCCCKKKKKKKKKKKKKKbbbaKaaKK..KKYyK',
    '..KKXxKKCccKaccccccKacccccccKabbaaaaKaaaK.KYyKK',
    '....KKKKKcccccccccKabbbbbbbbbKabaaaaaaaKKK.KK',
    '.....KCCCKKKcccccbKabbbbbbbbbKabbaaaKKKbbaK',
    'KK...CCccCCCKKcccKabbbbbbbbbbbKabaKKbbbaaaK...KK',
    'KxKKKCccccKaCCKKKKKKKKKKKKKKKKKKKKbbaKaaaaaKKKyK',
    '.KXxKCcccKacccCCCccccccKacccccbbbbaaaaKaaaaKYyK',
    '..KKKCcccccccccccbbbbbbKabbbbbbbbaaaaaaaaaaKKK',
    '....CCcccccccccccbbbbbKabbbbbbbbbaaaaaaaaaaK',
    '...KCCCCCCCCCCccccccccccccccccbbbbbbbbbbbbbbK',
    '...KKaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaKK',
    '.....KKMMMMMMMhhhhhhhhhhhhhhhhhhhhhhhhMMMMMMKK',
    '......KMMMMMhhHHHHhhhhhhhhhhhhhhhhHHHHhhMMMMK',
    '......KMMMMhHHKKKhhhKKKKKKKKKhhhhhhhKKKhHMMMK',
    '......KMMMhHhhhKKKhKRRRRRRrrrKhhhKKKhhhhhMMMK',
    '......KMMMhhhKeeEeKKRxRRRRrrqKhKKeEeeKhhhMMMK',
    '......KMMMhhhKKeeeeKRxRRRrrrqKhKeeeeKKhhhMMMK',
    '......KMMMMhhhhKKKKKKRRRRrrrqKKhKKKKhhhhMMMMK',
    '......KMMMMMhhhhhhhKMKRRRrrqKMKhhhhhhhhMMMMMK',
    '......KKMMMMMMhhhhhKqKKRRrrqKKqKhhhhMMMMMMKKK',
    '.......KKKKKMMMMMMhhKqKKRrqKKqKhMMMMMMKKKKK',
    '...KKxXKK............KK.KRqK.KK........KKYyKK',
    '...KxXcXK...............KrqK...........KYyYyK',
    '...KKKKKK................KK............KKKKKK',
    ],
  };

  // VITRINE SENTINEL: a walking museum display case. Brass cornice and plinth, glass with glints, a porcelain skull on a velvet cushion, stubby porcelain legs
  CAST.vitrine = {
    name: 'Vitrine Sentinel', group: 'bosses', w: 32, h: 44,
    pal: { K: '#1a1420', n: '#fff0a0', N: '#f0c048', o: '#b87c2c', O: '#6e4218', i: '#2c4260', j: '#44648a', J: '#6c90b4', G: '#b4dcf4', W: '#ffffff', P: '#f6f6fa', p: '#d2d6e4', q: '#9ca2bc', Q: '#5c6282', B: '#c4f0ff', b: '#4ca8e8', V: '#e05060', v: '#a82838', u: '#5c1020' },
    rows: [
    '...............KK',
    '..............KnNK',
    '.............KnNoOK',
    '..KKKKKKKKKKKKNNooKKKKKKKKKKKKK',
    '.KnnnnNNNNNNNNNNNNNNNNNNNNNNNoOK',
    '.KNNNNNNNNNNNNNNNNNNNNNNNNNNoooK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KnNNoNNoNNoNNoNNoNNoNNoNNoNNoOOK',
    'KoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOK',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    '.KnNKiiiiiiiiiiiiiiiiiiiiiiKoOK',
    '.KnNKNoGJGjjjjjjjjjjjjjjjOoKoOK',
    '.KnNKoGWGJGjjjjjjjjjjjjjGjOKoOK',
    '.KNoKjJGWGJjKKKKKKKKjjjjGjiKoOK',
    '.KNoKjjJGWGKPPPPPPPpKjjjGiiKoOK',
    '.KNoKjjjJGKPPPPPPPpppKjjGiiKoOK',
    '.KNoKjjjjJKPKKKPpqKKKKjiGiiKoOK',
    '.KNoKjjjjjKKBbBKpKBbBKjiGiiKoOK',
    '.KNoKijjjjKPKbKPpqKbKKiiGiiKoOK',
    '.KNoKiijjjjKPPPKKpqqKjiiiiiKoOK',
    '.KNoKiiijjjKPKPKpKqKKiiiiiiKOOK',
    '.KNoKiiiijjjKKKKKKKKiiiiiiiKOOK',
    '.KNoKiiiiKnVVVVVVvvvvvnKiiiKOOK',
    '.KNoKiiiKVVVVVVVVvvvvvvuKiiKOOK',
    '.KoOKiiiKvVVVVvvvvvvvvuuKiiKOOK',
    '.KoOKOJJJKnuuuuuuuuuuunKJJOKOOK',
    '.KoOKoJJJJKKKKKKKKKKKKKJJJOKOOK',
    '.KoOKoOJJJJJJJJJJJJJJJJJJOOKOOK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KnNNNNNNNNNNNNNNNNNNNNNNNNNNNooK',
    'KPPPPPPPPPPPPPPPPPPPPPPPPPPPppqK',
    'KPPppppppppKKKKKKKKKKpppppppppqK',
    'KPpppppppppKnNNNNNNoKpppppppppqK',
    'KPpqqqqqqqqKKKKKKKKKKqqqqqqqqqQK',
    'KoooooooooooooooooooooooooooOOOK',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    '..KPPppK..KqQK....KQQK.KPppqK',
    '..KPPPpqK.KqQK....KQQK.KPPpqqK',
    '..KPPPpqK.KqQK....KQQK.KPPpqqK',
    '...KPpqK..KoOK....KoOK..KPqqK',
    '...KPpqK..KKKK....KKKK..KPqQK',
    '...KPpqK................KPqQK',
    '..KNnooOK..............KNooOOK',
    '..KKKKKKK..............KKKKKKK',
    ],
  };

  // THE CURATOR (phase 1): porcelain egg head with a slit eye, dead-grey docent's coat hanging open on a lattice of blue light, long porcelain fingers
  CAST.curator_p1 = {
    name: 'The Curator', group: 'bosses', w: 40, h: 64,
    pal: { K: '#16141f', W: '#ffffff', P: '#eceef6', p: '#c4c8da', q: '#8e92ac', Q: '#5a5e7a', C: '#9a9cab', c: '#72748a', d: '#50526a', D: '#2e2f40', B: '#e8f8ff', b: '#9cd4ff', L: '#4c8ee0', l: '#243e78', n: '#f0c048', o: '#a8702a' },
    rows: [
    '.................KKKKKK',
    '...............KKWPPPPpKK',
    '..............KWPPPPPPppqK',
    '.............KWPPPPPPPPppqK',
    '.............KWPPPPKKPPppqK',
    '.............KPPPPKbBKPppqK',
    '.............KPPPPKLBKPpqqK',
    '.............KPPPPKbBKPpqqK',
    '...........KKKPPPPKLBKPpqqKKK',
    '..........KCcKPPPPKbBKppqqKddK',
    '..........KCcKpPPPKLbKppqqKcdK',
    '..........KCccKpPPPKKPppqKccdK',
    '..........KCccKppPPPPPpqqKccdK',
    '..........KCcccKppPPPppqKcccdK',
    '..........KCcccKKqpppqqKKcccdK',
    '..........KCccccDKqqqqKDccccdK',
    '.......KKKKCccccDDKKKKDDcccccKKKK',
    '.....KKCCCKCccccKDDKqKDDKccccKdddKK',
    '....KCCCCcKCcccKbDKqQKDbKcccKddddcdK',
    '....KCCccccKCcKLbBKpqKBbLKccKdddddcdK',
    '...KCCcccccKCKLbBBKPqKBBbLKcKddddddcK',
    '...KCcccccKKCKbKKKKPpKKKKbKdKKdddddcK',
    '...KCcccccKCKLbBbKPPpqKbBbLKdKdddddcK',
    '...KCccccKKCKbKKKKPppqKKKKbKdKKddddcK',
    '...KCccccKCcKLbBbKPPpqKbBbLKddKddddcK',
    '...KCccccKCcKbKKKKPppqKKKKbKddKddddcK',
    '...KCccccKCcKLbBbKPPpqKbBbLKddKddddcK',
    '...KCccccKCccKbKKKPppqKKKbKdddKddddcK',
    '...KCccccKCccKLbBKPPpqKbBLKdddKddddcK',
    '...KCcccKKCcccKbKKPppqKKbKddddKKdddcK',
    '...KCcccKCcccccKLKPPpqKbKdddddKdddcK',
    '...KCcccKCccccccKKPppqKKddddddKdddcK',
    '...KCcccKCccccccccKKqKKdddddddKdddcK',
    '...KCcccKCcccccccccKnoKdddddddKdddcK',
    '...KCcccKCcccccccccKooKdddddddKdddcK',
    '...KCcccKCccccccccccKKddddddddKdddcK',
    '...KCcccKCccccccccccKdddddddddKdddcK',
    '...KCcccKCccccccccccKdddddddddKdddcK',
    '...KCcccKCccccccccccKdddddddddKdddcK',
    '...KCcccKCcccccccccccKddddddddKdddcK',
    '...KCcccKCcccccccccccKddddddddKdddcK',
    '...KKCccKCcccccccccccKddddddddKddcKK',
    '...KPKKKKCcccccccccccKddddddddKKKKdK',
    '..KWPPpqKCcccccccccccKddddddddKpqqKK',
    '..KPPpqqKCccccccccccKDKdddddddKppqqK',
    '..KPKpKqKCccccccccccKDKdddddddKpKqKK',
    '..KPKpKqKCcccccccccKDDDKddddddKpKqKqK',
    '..KPKpKqKCcccccccccKDDDKddddddKpKqKqK',
    '..KPKpKqKCccccccccKDDDDDKdddddKpKqKqK',
    '..KPKpKKKCccccccccKDDDDDKdddddKKKqKqK',
    '..KPK.KKCcccccccccKDKKKDKddddddKKqKqK',
    '..KK...KCccccccccKDKPqKDKdddddKKKKqK',
    '.......KCccccccccKDKPqKDKdddddK..KKK',
    '......KCcccccccccKDKPqKDKddddddK',
    '......KCcccccccccKDKPqKDKddddddK',
    '......KCccccccccKDDKPqKDDKdddddK',
    '.....KCcccccccccKDKKPqKKDKddddddK',
    '.....KCCcccccccKKKPPpqqKKKddddddK',
    '.....KKKKCcccKKK.KPpqqqK.KKKddKKK',
    '.........KKKK....KPpqqK......KK',
    '................KPPpqqqK',
    '...............KWPppqqqK',
    '...............KKKKKKKKK',
    ],
  };
})();
