// Bakes PixelLab character exports into public/js/assets.js as data URIs, so
// the game still runs from file:// (no canvas tainting) and needs no server.
//
// Layout: assets/characters/<key>/metadata.json + <State>/rotations/<dir>.png
// (i.e. an unzipped PixelLab export). <key> must match a key in CHARACTERS.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const srcDir = path.join(root, 'assets/characters');
const out = {};

for (const key of fs.readdirSync(srcDir).sort()) {
  const dir = path.join(srcDir, key);
  const metaPath = path.join(dir, 'metadata.json');
  if (!fs.existsSync(metaPath)) continue;
  const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
  // Use the first state (usually "Idle") for the static battle sprite.
  const state = meta.states[0];
  const rotations = {};
  for (const [dirName, rel] of Object.entries(state.frames.rotations)) {
    const png = fs.readFileSync(path.join(dir, rel));
    rotations[dirName] = 'data:image/png;base64,' + png.toString('base64');
  }
  out[key] = { size: state.character.size, rotations };
  console.log(`${key}: ${Object.keys(rotations).length} directions`);
}

const js = `// Generated by tools/build-assets.mjs — do not edit by hand.\nwindow.CT = window.CT || {};\nCT.ASSETS = ${JSON.stringify(out)};\n`;
fs.writeFileSync(path.join(root, 'public/js/assets.js'), js);
console.log('wrote public/js/assets.js', (js.length / 1024).toFixed(1) + ' KiB');
